default:
    image: hub.ilearned.eu/i-learned/ci-cd/pelican-builder
    before_script:
        - apk add nodejs make
        - npm install node-sass
        - echo 'export PATH="$PATH:$HOME/node_modules/.bin"'
    tags:
        - AMD64

stages:
  - test-deploy
  - prod-deploy

test-deploy-job:
  stage: test-deploy
  script:
    - make

prod-deploy-job:
  stage: prod-deploy
  script:
    - make
    - rm -rf static/sass
    - apk add --no-cache openssh rsync
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo "$SSH_EBANVM01_PRIVATE_KEY" > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - rsync -az --delete -e "ssh -i ~/.ssh/id_ed25519" . deploy@vm01.eban.eu.org:/var/www/ilearned-analytics
  only:
  - main
