default:
    image: hub.ilearned.eu/i-learned/ci-cd/pelican-builder
    before_script:
        - apk add npm make
        - npm i node-sass
        - export PATH="$PATH:$HOME/node_modules/node-sass/bin"
    tags:
        - AMD64

stages:
  - test-deploy
  - prod-deploy

test-deploy-job:
  stage: test-deploy
  script:
    - make

prod-deploy-job:
  stage: prod-deploy
  script:
    - make
    - rm -rf static/sass node_modules
    - wget https://github.com/tdewolff/minify/releases/download/v2.10.0/minify_linux_amd64.tar.gz
    - tar -xf minify_linux_amd64.tar.gz -C /tmp
    - /tmp/minify -r -o ./ ./
    - apk add --no-cache openssh rsync
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo "$SSH_EBANVM01_PRIVATE_KEY" > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - rsync --delete-excluded="blog-french.json" --delete-excluded="blog-english.json"  -az --delete -e "ssh -i ~/.ssh/id_ed25519" . deploy@vm01.eban.eu.org:/var/www/ilearned-analytics
  only:
  - main
